### ISSUE TITLE
Pie chart segments are only labelled on hover

### ISSUE THREAD

**Issue by zarino** [mysociety/annual-report#2]
![screen shot 2015-02-04 at 11 59 26](https://cloud.githubusercontent.com/assets/739624/6040042/472c7d76-ac65-11e4-949e-5f4775c3b330.png)

This can be confusing when the (visually) left-most segment is actually the *second* item in the label below the chart.

How about putting little circles or squares of colour next to each item name?

![screen shot 2015-02-04 at 12 05 43](https://cloud.githubusercontent.com/assets/739624/6040113/2ad42718-ac66-11e4-99e2-d1fe4522bde3.png)

```scss
display: inline-block;
width: 1em;
height: 1em;
background-color: #fff;
vertical-align: -0.2em;
margin: 0 0.1em 0 0.3em;
border-radius: 3px;
opacity: 0.4; // or 0.6, or whatever
```

Are the colours different enough to be clearly associated between the chart and the key below?

**Comment by davewhiteland** [comment]
Please swap the labels round -- they simply need inverting: i.e. Puppies vs Kittens not Kittens vs Puppies, in each case. I presume the library/code/wotsit is painting them clockwise from the top, but wotevs: my eyes (in a left-to-right reading culture) don't care about that, they map left word to left space, right word to right.

...because the mouseover reveal is currently surprising when it should/need not be 

NB I also shake my fist at stooopid movie posters that plainly put the wrong names over the wrong faces. Stoopid Hollywood.
